// Preview-only fixture data. Active ONLY when NEXT_PUBLIC_DEV_PREVIEW=1 (see
// .env.local.example) so the UI can be reviewed before a real Supabase
// project + Google OAuth client exist. Has zero effect in production —
// every call site checks the flag first and falls through to the real
// Supabase-backed query otherwise.
import type { Profile, Project, Task } from "@/lib/types/database";

export const isDevPreview = () => process.env.NEXT_PUBLIC_DEV_PREVIEW === "1";

export const MOCK_OWNER: Profile = {
  id: "dev-owner",
  email: "minaikhan.saltanat@gmail.com",
  full_name: "Салтанат Минайхан",
  avatar_url: null,
  phone_whatsapp: "+7 708 627 9544",
  position: "Бас әкімші",
  skills: ["стратегия", "қаржы", "команда басқару"],
  role: "owner",
  locale: "kk",
  is_blocked: false,
  notification_channels: ["email", "inapp"],
  created_at: new Date().toISOString(),
};

export const MOCK_TEAM: Profile[] = [
  MOCK_OWNER,
  {
    ...MOCK_OWNER,
    id: "dev-almas",
    email: "almas@example.com",
    full_name: "Алмас Серіков",
    position: "Операциялық менеджер",
    role: "admin",
  },
  {
    ...MOCK_OWNER,
    id: "dev-miras",
    email: "miras@example.com",
    full_name: "Мирас Оспанов",
    position: "Маркетинг",
    role: "editor",
  },
  {
    ...MOCK_OWNER,
    id: "dev-vadim",
    email: "vadim@example.com",
    full_name: "Вадим Ким",
    position: "Хостел әкімшісі",
    role: "member",
  },
];

export const MOCK_PROJECTS: (Project & { logo_url: string })[] = [
  {
    id: "proj-1",
    name: "Almaty Central Hostel",
    logo_url: "https://placehold.co/128x128/16244A/FFFFFF.png?text=ACH",
    description: "Алматы орталығындағы негізгі хостел филиалы",
    website: "https://bayouteam.kz",
    goal: "2026 жылға қонақтар ағынын 30%-ға арттыру",
    deadline: "2026-12-31",
    status: "active",
    created_by: "dev-owner",
    archived_at: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "proj-2",
    name: "Алаколь филиалы — жазғы маусым",
    logo_url: "https://placehold.co/128x128/D9A52C/16244A.png?text=Alakol",
    description: "Жазғы маусымға дайындық: жөндеу, жарнама, брондау",
    website: "",
    goal: "Маусым 1-іне дейін толық ашылу",
    deadline: "2026-06-01",
    status: "active",
    created_by: "dev-owner",
    archived_at: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "proj-3",
    name: "Brand & маркетинг 2026",
    logo_url: "https://placehold.co/128x128/1D3161/FFFFFF.png?text=Brand",
    description: "Жаңа сайт, әлеуметтік желі, серіктестік бағдарламасы",
    website: "",
    goal: "Instagram аудиториясын 5000-ға жеткізу",
    deadline: "2026-09-30",
    status: "active",
    created_by: "dev-owner",
    archived_at: null,
    created_at: new Date().toISOString(),
  },
];

function inDays(days: number) {
  return new Date(Date.now() + days * 24 * 3600 * 1000).toISOString();
}

export const MOCK_TASKS: (Task & {
  project?: { id: string; name: string; logo_url: string | null };
  assignee?: { id: string; full_name: string | null; avatar_url: string | null } | null;
})[] = [
  {
    id: "task-1",
    project_id: "proj-1",
    title: "Ресепшн үшін жаңа кассалық жүйені баптау",
    description: "POS терминалын қосу, қызметкерлерге нұсқаулық беру",
    audio_url: null,
    transcript: null,
    assignee_id: "dev-almas",
    helpers: [],
    status: "in_progress",
    priority: "high",
    color: "#D9A52C",
    plan_scope: "week",
    due_at: inDays(-1),
    bonus_type: "money",
    bonus_value: "15 000 тг",
    checklist: [
      { id: "1", text: "Терминал сатып алу", done: true },
      { id: "2", text: "Интернетке қосу", done: true },
      { id: "3", text: "Қызметкерлерді оқыту", done: false },
    ],
    tags: ["ресепшн", "техника"],
    created_by: "dev-owner",
    position: 0,
    deleted_at: null,
    created_at: new Date().toISOString(),
    project: { id: "proj-1", name: "Almaty Central Hostel", logo_url: null },
    assignee: { id: "dev-almas", full_name: "Алмас Серіков", avatar_url: null },
  },
  {
    id: "task-2",
    project_id: "proj-1",
    title: "Booking.com рейтингін көтеру жоспары",
    description: "Соңғы 20 пікірді талдап, жақсарту тізімін жасау",
    audio_url: null,
    transcript: null,
    assignee_id: "dev-owner",
    helpers: ["dev-miras"],
    status: "todo",
    priority: "urgent",
    color: "#B23A3A",
    plan_scope: "day",
    due_at: inDays(0),
    bonus_type: null,
    bonus_value: null,
    checklist: [],
    tags: ["маркетинг"],
    created_by: "dev-owner",
    position: 0,
    deleted_at: null,
    created_at: new Date().toISOString(),
    project: { id: "proj-1", name: "Almaty Central Hostel", logo_url: null },
    assignee: { id: "dev-owner", full_name: "Салтанат Минайхан", avatar_url: null },
  },
  {
    id: "task-3",
    project_id: "proj-2",
    title: "Жаңа төсек-орындарын жеткізу",
    description: "12 екі қабатты кереует, матрац, жастық жиынтығы",
    audio_url: null,
    transcript: null,
    assignee_id: "dev-vadim",
    helpers: [],
    status: "todo",
    priority: "medium",
    color: null,
    plan_scope: "week",
    due_at: inDays(3),
    bonus_type: null,
    bonus_value: null,
    checklist: [
      { id: "1", text: "Жеткізушімен келісу", done: true },
      { id: "2", text: "Төлем жасау", done: false },
    ],
    tags: ["жабдық"],
    created_by: "dev-owner",
    position: 1,
    deleted_at: null,
    created_at: new Date().toISOString(),
    project: { id: "proj-2", name: "Алаколь филиалы — жазғы маусым", logo_url: null },
    assignee: { id: "dev-vadim", full_name: "Вадим Ким", avatar_url: null },
  },
  {
    id: "task-4",
    project_id: "proj-3",
    title: "Instagram Reels контент-жоспары — шілде",
    description: null,
    audio_url: null,
    transcript: null,
    assignee_id: "dev-miras",
    helpers: [],
    status: "in_review",
    priority: "medium",
    color: null,
    plan_scope: "month",
    due_at: inDays(7),
    bonus_type: "points",
    bonus_value: "30 ұпай",
    checklist: [],
    tags: ["SMM"],
    created_by: "dev-owner",
    position: 0,
    deleted_at: null,
    created_at: new Date().toISOString(),
    project: { id: "proj-3", name: "Brand & маркетинг 2026", logo_url: null },
    assignee: { id: "dev-miras", full_name: "Мирас Оспанов", avatar_url: null },
  },
  {
    id: "task-5",
    project_id: "proj-1",
    title: "Таза кір-жуу графигін бекіту",
    description: null,
    audio_url: null,
    transcript: null,
    assignee_id: "dev-vadim",
    helpers: [],
    status: "done",
    priority: "low",
    color: null,
    plan_scope: "week",
    due_at: inDays(-3),
    bonus_type: null,
    bonus_value: null,
    checklist: [],
    tags: [],
    created_by: "dev-owner",
    position: 2,
    deleted_at: null,
    created_at: new Date().toISOString(),
    project: { id: "proj-1", name: "Almaty Central Hostel", logo_url: null },
    assignee: { id: "dev-vadim", full_name: "Вадим Ким", avatar_url: null },
  },
];
